/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package kotlin.coroutines.task

import kotlin.brs.BrsInline
import kotlin.brs.Dynamic
import kotlin.brs.TaskComponent
import kotlin.brs.brsName
import kotlin.brs.createComponent
import kotlin.brs.roku.RoAssociativeArray
import kotlin.brs.roku.RoSGNode
import kotlin.brs.roku.RoSGNodeEvent
import kotlin.coroutines.Continuation
import kotlin.coroutines.ContinuationInterceptor
import kotlin.coroutines.intrinsics.COROUTINE_SUSPENDED
import kotlin.coroutines.intrinsics.suspendCoroutineUninterceptedOrReturn
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

/**
 * Render-side runner for typed task components ([TaskComponent] subclasses).
 *
 * The task-side half of the protocol is generated by the compiler: every
 * concrete task component gets a `__kotlinTaskMain` wrapper that calls the
 * user's `run()` override on the task thread, then reports completion through
 * the `kotlinTaskState`/`kotlinTaskError` protocol fields (error AA first,
 * state written last). This file is the render-side half: it starts the node,
 * observes `kotlinTaskState`, and resumes the awaiting coroutine when the
 * terminal state arrives.
 *
 * v1 constraints (all documented on [runTask]):
 * - must be called from render-thread component context: completion delivery
 *   uses the function-name observer form, whose callback resolves in the
 *   observing component's scope.
 * - a fresh unparented node is created per invocation; no pooling.
 * - no cancellation or timeout; one-shot tasks only.
 */

/**
 * Raised at the [runTask]/[awaitCompletion] suspend point when the task's
 * `run()` threw on the task thread. Carries the fields of the BrightScript
 * error object caught by the generated `__kotlinTaskMain` wrapper.
 */
public class TaskException(
    message: String,
    /** BrightScript runtime error number (0 when unavailable). */
    public val number: Int,
    /** BrightScript backtrace array captured at the throw site, if any. */
    public val backtrace: Dynamic?,
) : RuntimeException(message)

// Protocol field names (Roku interface fields declared by TaskComponent and
// inherited into every task component's XML; `control` is the native Task
// lifecycle field).
private const val TASK_STATE_FIELD: String = "kotlinTaskState"
private const val TASK_ERROR_FIELD: String = "kotlinTaskError"
private const val TASK_ID_FIELD: String = "kotlinTaskId"
private const val TASK_CONTROL_FIELD: String = "control"

/**
 * The typed task handle IS the raw roSGNode; this view makes the node API
 * (observe/setField) available to the runner without a wrapper object.
 */
@BrsInline("return task")
private external fun taskNodeOf(task: TaskComponent): RoSGNode

/**
 * [RoSGNodeEvent.getRoSGNode] with an honest return type: on device it returns
 * invalid when the event's node was destroyed between the event being queued
 * and delivered (device finding — see kotlin.test's DeviceTestLoop and the
 * Task 18 report; the typed interface declares it non-null).
 */
@BrsInline("return event.getRoSGNode()")
private external fun taskEventNodeOrNull(event: RoSGNodeEvent): RoSGNode?

/**
 * Continuation registry keyed by the `kotlinTaskId` protocol field. Each
 * [awaitCompletion] registers exactly one continuation per id; the observer
 * callback removes and resumes it when the task reports a terminal state.
 */
internal object TaskRunner {
    private val pending = mutableMapOf<Int, Continuation<Any?>>()
    private var lastTaskId: Int = 0

    /** Allocates the next correlation id (ids start at 1; 0 = unassigned). */
    fun allocateTaskId(): Int {
        lastTaskId = lastTaskId + 1
        return lastTaskId
    }

    fun hasPending(taskId: Int): Boolean = pending.containsKey(taskId)

    fun register(taskId: Int, continuation: Continuation<Any?>) {
        pending[taskId] = continuation
    }

    fun remove(taskId: Int): Continuation<Any?>? = pending.remove(taskId)
}

/**
 * Observer callback for `kotlinTaskState`. Top-level and in the same file as
 * the runner on purpose: it is registered by name (function-name observer
 * form), so it must live in a script that is included wherever [runTask] is
 * called — call-dependency tracking guarantees that for this file, since the
 * caller's component script calls into it.
 *
 * Guards use nested ifs throughout: BrightScript `and`/`or` do not
 * short-circuit, so the generated code must never rely on it.
 */
internal fun onKotlinTaskStateChanged(event: RoSGNodeEvent) {
    // Destroyed-node guard (Task 18 hardening): a completion event can outlive
    // its node; getRoSGNode() then returns invalid and any dot access crashes.
    val node = taskEventNodeOrNull(event)
    if (node == null) {
        return
    }
    val state = "${event.getData()}"
    if (state != "done") {
        if (state != "error") {
            // Initial default-value fire ("") or a non-terminal write: the
            // await stays armed.
            return
        }
    }
    val taskId = node.getField(TASK_ID_FIELD) as? Int
    if (taskId == null) {
        return
    }
    val continuation = TaskRunner.remove(taskId)
    if (continuation == null) {
        // No await registered (e.g. duplicate delivery after a double
        // observe, or a stale event) — drop it.
        return
    }
    // Unobserve BEFORE resuming, so a dropped node can be collected and the
    // resumed code never re-enters this observer. stillWatched-style guard
    // (DeviceTestLoop precedent): per-node ids are unique so no sibling await
    // can exist, but guard anyway rather than assume.
    if (!TaskRunner.hasPending(taskId)) {
        node.unobserveFieldScoped(TASK_STATE_FIELD)
    }
    if (state == "error") {
        resumeTask(continuation, node, true)
    } else {
        resumeTask(continuation, node, false)
    }
}

/**
 * Resumes an awaiting continuation with the completed node (or [TaskException]).
 * Resumption goes through the context's [ContinuationInterceptor] when present
 * (the delay()/yield() shape): the coroutine then continues on its dispatcher's
 * queue instead of deep inside this SceneGraph observer callback.
 */
private fun resumeTask(continuation: Continuation<Any?>, node: RoSGNode, failed: Boolean) {
    var target = continuation
    val interceptor = continuation.context[ContinuationInterceptor]
    if (interceptor != null) {
        target = interceptor.interceptContinuation(continuation)
    }
    if (failed) {
        target.resumeWithException(taskExceptionFrom(node))
    } else {
        target.resume(node)
    }
}

/** Builds a [TaskException] from the node's `kotlinTaskError` protocol AA. */
private fun taskExceptionFrom(node: RoSGNode): TaskException {
    var message = "Task failed"
    var number = 0
    var backtrace: Dynamic? = null
    val error = node.getField(TASK_ERROR_FIELD) as? RoAssociativeArray
    if (error != null) {
        val rawMessage = error.lookup("message")
        if (rawMessage != null) {
            message = "$rawMessage"
        }
        val rawNumber = error.lookup("number")
        if (rawNumber is Int) {
            number = rawNumber
        }
        backtrace = error.lookup("backtrace")
    }
    return TaskException(message, number, backtrace)
}

/**
 * Suspends until this task node reports a terminal `kotlinTaskState`, then
 * returns the node (so typed output fields can be read off it) or throws
 * [TaskException] if `run()` failed on the task thread.
 *
 * Un-sugared primitive behind [runTask]; also usable standalone on a node the
 * caller started manually. The observer is armed BEFORE the current state is
 * read, so a task that completes in the gap is caught by the fast path and a
 * task that completes later is caught by the observer — there is no window in
 * which a completion can be missed.
 *
 * Awaiting an already-completed node returns (or throws) immediately.
 * A concurrent second await on the same node throws [IllegalStateException]:
 * the registry holds exactly one continuation per task id.
 */
public suspend fun <T : TaskComponent> T.awaitCompletion(): T {
    val node = taskNodeOf(this)
    var assignedId = this.kotlinTaskId
    if (assignedId == 0) {
        assignedId = TaskRunner.allocateTaskId()
        this.kotlinTaskId = assignedId
    }
    // val so the suspension block below captures an immutable (no shared box).
    val taskId = assignedId
    // Double-await guard BEFORE the arm: unobserveFieldScoped removes every
    // observer this scope holds on the field, so disarming on this error path
    // would also strip the first awaiter's observer and strand its
    // continuation. Bailing before the arm leaks nothing and leaves the
    // pending await intact; past this point no await is pending, so the fast
    // paths below may unobserve unconditionally.
    if (TaskRunner.hasPending(taskId)) {
        throw IllegalStateException("Task node (kotlinTaskId=$taskId) is already being awaited")
    }
    node.observeFieldScoped(TASK_STATE_FIELD, brsName(::onKotlinTaskStateChanged))
    val state = this.kotlinTaskState
    if (state == "done") {
        node.unobserveFieldScoped(TASK_STATE_FIELD)
        return this
    }
    if (state == "error") {
        node.unobserveFieldScoped(TASK_STATE_FIELD)
        throw taskExceptionFrom(node)
    }
    // Tail-delegating suspension (the stdlib delay() shape — stdlib suspend
    // functions get no state machine, so the suspension must be the last step).
    return suspendCoroutineUninterceptedOrReturn { continuation ->
        @Suppress("UNCHECKED_CAST")
        TaskRunner.register(taskId, continuation as Continuation<Any?>)
        COROUTINE_SUSPENDED
    }
}

/**
 * Implementation target of [runTask]; the backend rewrites reified
 * `runTask<T>(configure)` call sites into
 * `runTaskImpl(brsCreateComponent<T>(), configure)` because klib inline
 * functions are never inlined at user call sites (BrsInlineFunctionResolver
 * limitation) — the rewrite performs exactly the one inline step the resolver
 * cannot. Keep this signature in sync with BrsRunTaskCallLowering.
 *
 * The observer is armed before `control=RUN` (the spike-proven order): a field
 * write on the task thread is only delivered to observers that were attached
 * when the write happened, so arming after RUN could miss a fast task's
 * terminal write entirely. [awaitCompletion]'s own arm + fast path makes its
 * second observe harmless (duplicate deliveries find no continuation).
 */
@PublishedApi
internal suspend fun <T : TaskComponent> runTaskImpl(task: T, configure: T.() -> Unit): T {
    task.configure()
    task.kotlinTaskId = TaskRunner.allocateTaskId()
    val node = taskNodeOf(task)
    node.observeFieldScoped(TASK_STATE_FIELD, brsName(::onKotlinTaskStateChanged))
    node.setField(TASK_CONTROL_FIELD, "RUN")
    return task.awaitCompletion()
}

/**
 * Creates a fresh unparented node of task component [T], applies [configure]
 * to set its typed input fields, starts it (`control=RUN`), and suspends until
 * `run()` completes on the task thread. Returns the completed node so typed
 * output fields can be read off it; throws [TaskException] if `run()` threw.
 *
 * ```kotlin
 * val task = runTask<FetchFeedTask> { url = "https://..." }
 * show(task.feed)
 * ```
 *
 * v1 constraints:
 * - Call from render-thread component context only (scene/component handlers
 *   and coroutines launched from them). Completion uses the function-name
 *   observer form, which resolves its callback in the observing component's
 *   scope; the main-thread driver context is not supported.
 * - One-shot: no cancellation, no timeout, no node reuse. Every invocation
 *   creates a fresh node; concurrent invocations of the same task type are
 *   independent nodes correlated by `kotlinTaskId`.
 */
public suspend inline fun <reified T : TaskComponent> runTask(noinline configure: T.() -> Unit): T =
    runTaskImpl(createComponent<T>(), configure)
