/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.fir.extensions.brs

import org.jetbrains.kotlin.GeneratedDeclarationKey
import org.jetbrains.kotlin.descriptors.ClassKind
import org.jetbrains.kotlin.descriptors.Modality
import org.jetbrains.kotlin.fir.FirElement
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.declarations.FirSimpleFunction
import org.jetbrains.kotlin.fir.declarations.utils.isCompanion
import org.jetbrains.kotlin.fir.expressions.FirBlock
import org.jetbrains.kotlin.fir.expressions.FirFunctionCall
import org.jetbrains.kotlin.fir.expressions.FirLiteralExpression
import org.jetbrains.kotlin.fir.expressions.FirNamedArgumentExpression
import org.jetbrains.kotlin.fir.extensions.*
import org.jetbrains.kotlin.fir.references.FirNamedReference
import org.jetbrains.kotlin.fir.visitors.FirVisitor
import org.jetbrains.kotlin.fir.plugin.createConstructor
import org.jetbrains.kotlin.fir.plugin.createMemberProperty
import org.jetbrains.kotlin.fir.plugin.createNestedClass
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirConstructorSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirPropertySymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.fir.symbols.resolvedAnnotationsWithArguments
import org.jetbrains.kotlin.fir.declarations.toAnnotationClassIdSafe
import org.jetbrains.kotlin.fir.types.constructClassLikeType
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames

/**
 * FIR extension that generates a nested Layout class for classes with @SGLayout companion functions.
 *
 * For a class like:
 * ```kotlin
 * class MainScreen : SceneNodeComponent() {
 *     companion object {
 *         @SGLayout
 *         fun defineLayout() = sceneLayout {
 *             layoutGroup(id = "mainLayout") {
 *                 button(id = "myButton", text = "Click me")
 *                 label(id = "myLabel", text = "Hello")
 *             }
 *         }
 *     }
 *
 *     val layout = Layout(top)
 * }
 * ```
 *
 * This generator:
 * 1. Finds companion functions annotated with @SGLayout
 * 2. Extracts node IDs by parsing the DSL lambda body (looking for calls like `button(id = "xyz")`)
 * 3. Creates a nested class `MainScreen.Layout` with a constructor taking `RoSGNode`
 * 4. Generates properties for each extracted node ID, each returning `RoSGNode`
 *
 * The actual BrightScript implementation (lazy findNode with caching) is generated by the IR backend.
 */
class SceneGraphLayoutGenerator(session: FirSession) : FirDeclarationGenerationExtension(session) {

    companion object {
        private val SGLAYOUT_CLASS_ID = ClassId.fromString("kotlin/brs/scenegraph/SGLayout")
        private val ROSGNODE_CLASS_ID = ClassId.fromString("kotlin/brs/roku/RoSGNode")
        private val LAYOUT_CLASS_NAME = Name.identifier("Layout")
    }

    /**
     * Information about an @SGLayout function extracted from a companion object.
     */
    data class LayoutInfo(
        val functionName: Name,
        val nodeIds: List<String>
    )

    // Cache: outer class ID -> layout info (to avoid re-parsing annotations)
    private val layoutInfoCache = mutableMapOf<ClassId, LayoutInfo?>()

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(SceneGraphPredicates.HAS_SGLAYOUT_FUNCTION)
    }

    // ===== Nested Class Generation =====

    /**
     * Returns the names of nested classes to generate for the given class.
     * If the class has a companion with @SGLayout function, we generate a `Layout` class.
     */
    override fun getNestedClassifiersNames(
        classSymbol: FirClassSymbol<*>,
        context: NestedClassGenerationContext
    ): Set<Name> {
        // Skip companion objects - we generate Layout on the outer class
        if (classSymbol is FirRegularClassSymbol && classSymbol.isCompanion) {
            return emptySet()
        }

        val layoutInfo = getLayoutInfo(classSymbol) ?: return emptySet()
        if (layoutInfo.nodeIds.isEmpty()) return emptySet()

        return setOf(LAYOUT_CLASS_NAME)
    }

    /**
     * Generates the nested Layout class.
     */
    override fun generateNestedClassLikeDeclaration(
        owner: FirClassSymbol<*>,
        name: Name,
        context: NestedClassGenerationContext
    ): FirClassLikeSymbol<*>? {
        if (name != LAYOUT_CLASS_NAME) return null

        val layoutInfo = getLayoutInfo(owner) ?: return null
        if (layoutInfo.nodeIds.isEmpty()) return null

        // Generate: class Layout { ... }
        return createNestedClass(
            owner,
            LAYOUT_CLASS_NAME,
            SGLayoutKey,
            ClassKind.CLASS
        ) {
            modality = Modality.FINAL
        }.symbol
    }

    // ===== Member Generation on Layout Class =====

    /**
     * Returns the names of callables to generate for the given class.
     * For generated Layout classes, returns constructor + node IDs as property names.
     */
    override fun getCallableNamesForClass(
        classSymbol: FirClassSymbol<*>,
        context: MemberGenerationContext
    ): Set<Name> {
        // Check if this is a generated Layout class
        if (classSymbol.name != LAYOUT_CLASS_NAME) return emptySet()

        val ownerClassId = classSymbol.classId.outerClassId ?: return emptySet()
        val ownerSymbol = session.symbolProvider.getClassLikeSymbolByClassId(ownerClassId)
            as? FirClassSymbol<*> ?: return emptySet()

        val layoutInfo = getLayoutInfo(ownerSymbol) ?: return emptySet()
        if (layoutInfo.nodeIds.isEmpty()) return emptySet()

        // Return constructor + node IDs as property names
        val names = mutableSetOf<Name>()
        names.add(SpecialNames.INIT) // Constructor
        names.addAll(layoutInfo.nodeIds.map { Name.identifier(it) })
        return names
    }

    /**
     * Generates the constructor for the Layout class.
     */
    override fun generateConstructors(context: MemberGenerationContext): List<FirConstructorSymbol> {
        val owner = context.owner
        if (owner.name != LAYOUT_CLASS_NAME) return emptyList()

        val ownerClassId = owner.classId.outerClassId ?: return emptyList()
        val ownerSymbol = session.symbolProvider.getClassLikeSymbolByClassId(ownerClassId)
            as? FirClassSymbol<*> ?: return emptyList()

        val layoutInfo = getLayoutInfo(ownerSymbol) ?: return emptyList()
        if (layoutInfo.nodeIds.isEmpty()) return emptyList()

        // Generate constructor: Layout(top: RoSGNode)
        val roSGNodeType = ROSGNODE_CLASS_ID.constructClassLikeType(emptyArray(), isMarkedNullable = false)
        val constructor = createConstructor(
            owner,
            SGLayoutKey,
            isPrimary = true
        ) {
            valueParameter(Name.identifier("top"), roSGNodeType)
        }
        return listOf(constructor.symbol)
    }

    /**
     * Generates properties for the Layout class.
     * Each property returns RoSGNode and corresponds to a node ID from the @SGLayout annotation.
     */
    override fun generateProperties(
        callableId: CallableId,
        context: MemberGenerationContext?
    ): List<FirPropertySymbol> {
        val owner = context?.owner ?: return emptyList()

        // Verify this is a generated Layout class
        if (owner.name != LAYOUT_CLASS_NAME) return emptyList()

        val ownerClassId = owner.classId.outerClassId ?: return emptyList()
        val outerSymbol = session.symbolProvider.getClassLikeSymbolByClassId(ownerClassId)
            as? FirClassSymbol<*> ?: return emptyList()

        val layoutInfo = getLayoutInfo(outerSymbol) ?: return emptyList()
        if (callableId.callableName.asString() !in layoutInfo.nodeIds) return emptyList()

        // Generate property returning RoSGNode
        val roSGNodeType = ROSGNODE_CLASS_ID.constructClassLikeType(emptyArray(), isMarkedNullable = false)
        val property = createMemberProperty(
            owner,
            SGLayoutKey,
            callableId.callableName,
            roSGNodeType,
            isVal = true,
            hasBackingField = false // The actual backing is generated by IR backend
        )
        return listOf(property.symbol)
    }

    // ===== Helper Methods =====

    /**
     * Gets or computes layout info for the given class by checking its companion object.
     */
    private fun getLayoutInfo(classSymbol: FirClassSymbol<*>): LayoutInfo? {
        val classId = classSymbol.classId
        return layoutInfoCache.getOrPut(classId) {
            extractLayoutInfoFromCompanion(classSymbol)
        }
    }

    /**
     * Extracts layout info from the companion object of a class.
     * Finds @SGLayout-annotated functions and extracts node IDs from the DSL body.
     * Returns null if no companion or no @SGLayout function found.
     */
    @OptIn(
        org.jetbrains.kotlin.fir.declarations.DirectDeclarationsAccess::class,
        org.jetbrains.kotlin.fir.symbols.SymbolInternals::class
    )
    private fun extractLayoutInfoFromCompanion(classSymbol: FirClassSymbol<*>): LayoutInfo? {
        // Find the companion object
        val companionSymbol = classSymbol.fir.declarations
            .filterIsInstance<org.jetbrains.kotlin.fir.declarations.FirRegularClass>()
            .find { it.status.isCompanion }
            ?.symbol ?: return null

        // Find functions with @SGLayout annotation in the companion
        val functions = companionSymbol.fir.declarations.filterIsInstance<FirSimpleFunction>()

        for (function in functions) {
            // Use safe version to handle unresolved annotations
            val hasAnnotation = function.symbol.resolvedAnnotationsWithArguments.any {
                it.toAnnotationClassIdSafe(session) == SGLAYOUT_CLASS_ID
            }
            if (!hasAnnotation) continue

            // Extract node IDs from function body by traversing the DSL
            val nodeIds = extractNodeIdsFromFunctionBody(function.body)
            if (nodeIds.isEmpty()) continue

            return LayoutInfo(function.name, nodeIds)
        }
        return null
    }

    /**
     * Extract node IDs from the DSL lambda body.
     * Traverses the FIR tree looking for calls like `button(id = "xyz")`.
     *
     * At the COMPANION_GENERATION phase, the function body exists but expressions
     * haven't been fully resolved. We traverse the raw FIR tree to find function calls.
     */
    private fun extractNodeIdsFromFunctionBody(body: FirBlock?): List<String> {
        if (body == null) return emptyList()

        val nodeIds = mutableListOf<String>()

        // Traverse the entire body tree, not just direct children
        body.accept(NodeIdExtractorVisitor(nodeIds), Unit)

        return nodeIds
    }

    /**
     * DSL builder method names that take an `id` parameter.
     */
    private val dslBuilderMethods = setOf(
        "group", "layoutGroup", "label", "poster", "rectangle",
        "button", "buttonGroup", "textEditBox", "keyboard"
    )

    /**
     * FIR visitor that extracts node IDs from DSL builder method calls.
     *
     * Traverses the entire FIR tree looking for function calls to DSL builder
     * methods like `button(id = "xyz")`. Works with raw/unresolved FIR.
     */
    private inner class NodeIdExtractorVisitor(
        private val nodeIds: MutableList<String>
    ) : FirVisitor<Unit, Unit>() {

        override fun visitElement(element: FirElement, data: Unit) {
            element.acceptChildren(this, data)
        }

        override fun visitFunctionCall(functionCall: FirFunctionCall, data: Unit) {
            val callName = (functionCall.calleeReference as? FirNamedReference)?.name?.asString()

            if (callName in dslBuilderMethods) {
                // Extract "id" named argument
                extractIdArgument(functionCall)?.let { nodeIds.add(it) }
            }

            // Continue traversing into lambda arguments (for nested containers)
            functionCall.acceptChildren(this, data)
        }

        /**
         * Extract the string value of the "id" named argument from a function call.
         *
         * At raw FIR stage, named arguments are FirNamedArgumentExpression nodes.
         * Also handles positional arguments where `id` is the first parameter.
         */
        private fun extractIdArgument(call: FirFunctionCall): String? {
            val arguments = call.argumentList.arguments
            if (arguments.isEmpty()) return null

            // Check for named argument `id = "value"`
            for (arg in arguments) {
                if (arg is FirNamedArgumentExpression && arg.name.asString() == "id") {
                    val valueExpr = arg.expression
                    if (valueExpr is FirLiteralExpression && valueExpr.value is String) {
                        return valueExpr.value as String
                    }
                }
            }

            // Check first positional argument (id is always the first parameter in our DSL)
            val firstArg = arguments.firstOrNull()
            // Handle the case where it's a direct literal (positional)
            if (firstArg is FirLiteralExpression && firstArg.value is String) {
                return firstArg.value as String
            }
            // Handle named argument as first arg
            if (firstArg is FirNamedArgumentExpression) {
                val valueExpr = firstArg.expression
                if (valueExpr is FirLiteralExpression && valueExpr.value is String) {
                    // Only use if it's the id parameter
                    if (firstArg.name.asString() == "id") {
                        return valueExpr.value as String
                    }
                }
            }

            return null
        }
    }

    /**
     * Key for identifying generated declarations from this extension.
     */
    object SGLayoutKey : GeneratedDeclarationKey() {
        override fun toString(): String = "SGLayoutKey"
    }
}
