/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.fir.extensions.brs

import org.jetbrains.kotlin.GeneratedDeclarationKey
import org.jetbrains.kotlin.descriptors.ClassKind
import org.jetbrains.kotlin.descriptors.Modality
import org.jetbrains.kotlin.fir.FirElement
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.declarations.FirSimpleFunction
import org.jetbrains.kotlin.fir.declarations.utils.isCompanion
import org.jetbrains.kotlin.fir.expressions.FirBlock
import org.jetbrains.kotlin.fir.expressions.FirFunctionCall
import org.jetbrains.kotlin.fir.expressions.FirLiteralExpression
import org.jetbrains.kotlin.fir.expressions.FirNamedArgumentExpression
import org.jetbrains.kotlin.fir.extensions.*
import org.jetbrains.kotlin.fir.references.FirNamedReference
import org.jetbrains.kotlin.fir.visitors.FirVisitor
import org.jetbrains.kotlin.fir.plugin.createConstructor
import org.jetbrains.kotlin.fir.plugin.createMemberProperty
import org.jetbrains.kotlin.fir.plugin.createTopLevelClass
import org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirConstructorSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirPropertySymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.fir.symbols.resolvedAnnotationsWithArguments
import org.jetbrains.kotlin.fir.declarations.toAnnotationClassIdSafe
import org.jetbrains.kotlin.fir.types.constructClassLikeType
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames

/**
 * FIR extension that generates a top-level Layout class for classes with @SGLayout companion functions.
 *
 * @deprecated This FIR generator has been replaced by Gradle-based source generation.
 * Layout classes are now generated as actual `.kt` source files by GenerateLayoutStubsTask
 * in the kotlin-roku Gradle plugin. This provides:
 * 1. Full IDE support (code completion, navigation, type checking)
 * 2. No duplicate class conflicts
 * 3. Easier debugging (can inspect generated source files)
 *
 * This file is kept for reference. See BrsFirExtensionRegistrar for the removal note.
 *
 * Original design:
 * For a class like:
 * ```kotlin
 * class MainScreen : SceneComponent() {
 *     companion object {
 *         @SGLayout
 *         fun defineLayout() = sceneLayout {
 *             layoutGroup(id = "mainLayout") {
 *                 button(id = "myButton", text = "Click me")
 *                 label(id = "myLabel", text = "Hello")
 *             }
 *         }
 *     }
 *
 *     val layout = MainScreen_Layout(top)
 * }
 * ```
 *
 * This generator:
 * 1. Finds companion functions annotated with @SGLayout
 * 2. Extracts node IDs by parsing the DSL lambda body (looking for calls like `button(id = "xyz")`)
 * 3. Creates a top-level class `MainScreen_Layout` with a constructor taking `RoSGNode`
 * 4. Generates properties for each extracted node ID, each returning `RoSGNode`
 *
 * The actual BrightScript implementation (lazy findNode with caching) is generated by the IR backend.
 */
@OptIn(ExperimentalTopLevelDeclarationsGenerationApi::class)
class SceneGraphLayoutGenerator(session: FirSession) : FirDeclarationGenerationExtension(session) {

    companion object {
        private val SGLAYOUT_CLASS_ID = ClassId.fromString("kotlin/brs/scenegraph/SGLayout")
        private val ROSGNODE_CLASS_ID = ClassId.fromString("kotlin/brs/roku/RoSGNode")
    }

    /**
     * Information about an @SGLayout function extracted from a companion object.
     */
    data class LayoutInfo(
        val ownerClassId: ClassId,
        val functionName: Name,
        val nodeIds: List<String>
    )

    private val predicateBasedProvider = session.predicateBasedProvider

    /**
     * Lazily discover all classes with @SGLayout companion functions.
     * This is computed once and cached.
     */
    private val matchedClasses: List<FirRegularClassSymbol> by lazy {
        predicateBasedProvider.getSymbolsByPredicate(SceneGraphPredicates.HAS_SGLAYOUT_FUNCTION)
            .filterIsInstance<FirRegularClassSymbol>()
            .filter { !it.isCompanion }  // Skip companion objects themselves
    }

    /**
     * Map from layout class ID to layout info (owner class + node IDs).
     * Lazily computed after matchedClasses is populated.
     */
    private val layoutClassInfoMap: Map<ClassId, LayoutInfo> by lazy {
        val result = mutableMapOf<ClassId, LayoutInfo>()
        for (classSymbol in matchedClasses) {
            val layoutInfo = extractLayoutInfoFromCompanion(classSymbol)
            if (layoutInfo != null && layoutInfo.nodeIds.isNotEmpty()) {
                val layoutClassId = createLayoutClassId(classSymbol.classId)
                result[layoutClassId] = layoutInfo
            }
        }
        result
    }

    /**
     * Set of all packages that contain generated Layout classes.
     */
    private val packagesWithGeneratedClasses: Set<FqName> by lazy {
        layoutClassInfoMap.keys.mapTo(mutableSetOf()) { it.packageFqName }
    }

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(SceneGraphPredicates.HAS_SGLAYOUT_FUNCTION)
    }

    // ===== Top-Level Class Generation =====

    /**
     * Returns the class IDs of top-level classes to generate.
     * For each class with @SGLayout function, we generate a `ClassName_Layout` class.
     */
    override fun getTopLevelClassIds(): Set<ClassId> {
        return layoutClassInfoMap.keys
    }

    /**
     * Indicates which packages we provide generated classes for.
     */
    override fun hasPackage(packageFqName: FqName): Boolean {
        return packageFqName in packagesWithGeneratedClasses
    }

    /**
     * Generates a top-level Layout class for the given class ID.
     */
    override fun generateTopLevelClassLikeDeclaration(classId: ClassId): FirClassLikeSymbol<*>? {
        // Check if this is a layout class we should generate
        val layoutInfo = layoutClassInfoMap[classId] ?: return null
        if (layoutInfo.nodeIds.isEmpty()) return null

        // Generate: class OwnerName_Layout { ... }
        return createTopLevelClass(
            classId,
            SGLayoutKey,
            ClassKind.CLASS
        ) {
            modality = Modality.FINAL
        }.symbol
    }

    // ===== Member Generation on Layout Class =====

    /**
     * Returns the names of callables to generate for the given class.
     * For generated Layout classes, returns constructor + node IDs as property names.
     */
    override fun getCallableNamesForClass(
        classSymbol: FirClassSymbol<*>,
        context: MemberGenerationContext
    ): Set<Name> {
        // Check if this is a generated Layout class (top-level)
        val layoutInfo = layoutClassInfoMap[classSymbol.classId] ?: return emptySet()
        if (layoutInfo.nodeIds.isEmpty()) return emptySet()

        // Return constructor + node IDs as property names
        val names = mutableSetOf<Name>()
        names.add(SpecialNames.INIT) // Constructor
        names.addAll(layoutInfo.nodeIds.map { Name.identifier(it) })
        return names
    }

    /**
     * Generates the constructor for the Layout class.
     */
    override fun generateConstructors(context: MemberGenerationContext): List<FirConstructorSymbol> {
        val owner = context.owner
        val layoutInfo = layoutClassInfoMap[owner.classId] ?: return emptyList()
        if (layoutInfo.nodeIds.isEmpty()) return emptyList()

        // Generate constructor: OwnerName_Layout(top: RoSGNode)
        val roSGNodeType = ROSGNODE_CLASS_ID.constructClassLikeType(emptyArray(), isMarkedNullable = false)
        val constructor = createConstructor(
            owner,
            SGLayoutKey,
            isPrimary = true
        ) {
            valueParameter(Name.identifier("top"), roSGNodeType)
        }
        return listOf(constructor.symbol)
    }

    /**
     * Generates properties for the Layout class.
     * Each property returns RoSGNode and corresponds to a node ID from the @SGLayout annotation.
     */
    override fun generateProperties(
        callableId: CallableId,
        context: MemberGenerationContext?
    ): List<FirPropertySymbol> {
        val owner = context?.owner ?: return emptyList()
        val layoutInfo = layoutClassInfoMap[owner.classId] ?: return emptyList()
        if (callableId.callableName.asString() !in layoutInfo.nodeIds) return emptyList()

        // Generate property returning RoSGNode
        val roSGNodeType = ROSGNODE_CLASS_ID.constructClassLikeType(emptyArray(), isMarkedNullable = false)
        val property = createMemberProperty(
            owner,
            SGLayoutKey,
            callableId.callableName,
            roSGNodeType,
            isVal = true,
            hasBackingField = false // The actual backing is generated by IR backend
        )
        return listOf(property.symbol)
    }

    // ===== Helper Methods =====

    /**
     * Creates the class ID for a Layout class given the owner class ID.
     * E.g., com.example.MainScreen -> com.example.MainScreen_Layout
     */
    private fun createLayoutClassId(ownerClassId: ClassId): ClassId {
        val layoutClassName = Name.identifier("${ownerClassId.shortClassName.asString()}_Layout")
        return ClassId(ownerClassId.packageFqName, layoutClassName)
    }

    /**
     * Extracts layout info from the companion object of a class.
     * Finds @SGLayout-annotated functions and extracts node IDs from the DSL body.
     * Returns null if no companion or no @SGLayout function found.
     */
    @OptIn(
        org.jetbrains.kotlin.fir.declarations.DirectDeclarationsAccess::class,
        org.jetbrains.kotlin.fir.symbols.SymbolInternals::class
    )
    private fun extractLayoutInfoFromCompanion(classSymbol: FirRegularClassSymbol): LayoutInfo? {
        // Find the companion object
        val companionSymbol = classSymbol.fir.declarations
            .filterIsInstance<org.jetbrains.kotlin.fir.declarations.FirRegularClass>()
            .find { it.status.isCompanion }
            ?.symbol ?: return null

        // Find functions with @SGLayout annotation in the companion
        val functions = companionSymbol.fir.declarations.filterIsInstance<FirSimpleFunction>()

        for (function in functions) {
            // Use safe version to handle unresolved annotations
            val hasAnnotation = function.symbol.resolvedAnnotationsWithArguments.any {
                it.toAnnotationClassIdSafe(session) == SGLAYOUT_CLASS_ID
            }
            if (!hasAnnotation) continue

            // Extract node IDs from function body by traversing the DSL
            val nodeIds = extractNodeIdsFromFunctionBody(function.body)
            if (nodeIds.isEmpty()) continue

            return LayoutInfo(classSymbol.classId, function.name, nodeIds)
        }
        return null
    }

    /**
     * Extract node IDs from the DSL lambda body.
     * Traverses the FIR tree looking for calls like `button(id = "xyz")`.
     *
     * At the COMPANION_GENERATION phase, the function body exists but expressions
     * haven't been fully resolved. We traverse the raw FIR tree to find function calls.
     */
    private fun extractNodeIdsFromFunctionBody(body: FirBlock?): List<String> {
        if (body == null) return emptyList()

        val nodeIds = mutableListOf<String>()

        // Traverse the entire body tree, not just direct children
        body.accept(NodeIdExtractorVisitor(nodeIds), Unit)

        return nodeIds
    }

    /**
     * DSL builder method names that take an `id` parameter.
     * Note: "component" has `id` as its 2nd parameter (after componentType).
     */
    private val dslBuilderMethods = setOf(
        "group", "layoutGroup", "label", "poster", "rectangle",
        "button", "buttonGroup", "textEditBox", "keyboard", "component"
    )

    /**
     * FIR visitor that extracts node IDs from DSL builder method calls.
     *
     * Traverses the entire FIR tree looking for function calls to DSL builder
     * methods like `button(id = "xyz")`. Works with raw/unresolved FIR.
     */
    private inner class NodeIdExtractorVisitor(
        private val nodeIds: MutableList<String>
    ) : FirVisitor<Unit, Unit>() {

        override fun visitElement(element: FirElement, data: Unit) {
            element.acceptChildren(this, data)
        }

        override fun visitFunctionCall(functionCall: FirFunctionCall, data: Unit) {
            val callName = (functionCall.calleeReference as? FirNamedReference)?.name?.asString()

            if (callName in dslBuilderMethods) {
                // Extract "id" named argument
                extractIdArgument(functionCall)?.let { nodeIds.add(it) }
            }

            // Continue traversing into lambda arguments (for nested containers)
            functionCall.acceptChildren(this, data)
        }

        /**
         * Extract the string value of the "id" named argument from a function call.
         *
         * At raw FIR stage, named arguments are FirNamedArgumentExpression nodes.
         * Also handles positional arguments where `id` is typically the first parameter.
         * For `component()` calls, `id` is the second parameter (after componentType).
         */
        private fun extractIdArgument(call: FirFunctionCall): String? {
            val arguments = call.argumentList.arguments
            if (arguments.isEmpty()) return null

            val callName = (call.calleeReference as? FirNamedReference)?.name?.asString()
            val isComponentCall = callName == "component"

            // Check for named argument `id = "value"`
            for (arg in arguments) {
                if (arg is FirNamedArgumentExpression && arg.name.asString() == "id") {
                    val valueExpr = arg.expression
                    if (valueExpr is FirLiteralExpression && valueExpr.value is String) {
                        return valueExpr.value as String
                    }
                }
            }

            // For component(), id is the second positional argument
            if (isComponentCall) {
                if (arguments.size >= 2) {
                    val secondArg = arguments[1]
                    // Direct literal
                    if (secondArg is FirLiteralExpression && secondArg.value is String) {
                        return secondArg.value as String
                    }
                    // Named argument in second position
                    if (secondArg is FirNamedArgumentExpression && secondArg.name.asString() == "id") {
                        val valueExpr = secondArg.expression
                        if (valueExpr is FirLiteralExpression && valueExpr.value is String) {
                            return valueExpr.value as String
                        }
                    }
                }
                return null
            }

            // For other DSL methods, id is the first positional argument
            val firstArg = arguments.firstOrNull()
            // Handle the case where it's a direct literal (positional)
            if (firstArg is FirLiteralExpression && firstArg.value is String) {
                return firstArg.value as String
            }
            // Handle named argument as first arg
            if (firstArg is FirNamedArgumentExpression) {
                val valueExpr = firstArg.expression
                if (valueExpr is FirLiteralExpression && valueExpr.value is String) {
                    // Only use if it's the id parameter
                    if (firstArg.name.asString() == "id") {
                        return valueExpr.value as String
                    }
                }
            }

            return null
        }
    }

    /**
     * Key for identifying generated declarations from this extension.
     */
    object SGLayoutKey : GeneratedDeclarationKey() {
        override fun toString(): String = "SGLayoutKey"
    }
}
